In [1]:
import pandas as pd
import torch
%load_ext autoreload
%autoreload 2

In [2]:
from transformers import GPTNeoForSequenceClassification, GPTNeoForCausalLM, GPT2Tokenizer
from model import GPTNeoForSequenceClassificationBinary
from dataset import PairPredictionDataModule
model = GPTNeoForSequenceClassificationBinary.from_pretrained("/notebooks/results/checkpoint-1318")
tokenizer = GPT2Tokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")

In [10]:
from dataset import get_taxonomy_dataset, get_taxonomy_dataset_binary
dataset = get_taxonomy_dataset_binary('/notebooks/test_all.csv', entire_dataset=True,remove_columns=True)

Using custom data configuration default-9ee1c420eec116cd
Reusing dataset csv (/root/.cache/huggingface/datasets/csv/default-9ee1c420eec116cd/0.0.0/51cce309a08df9c4d82ffd9363bbe090bf173197fc01a71b034e8594995a1a58)

  0%|          | 0/17461 [00:00<?, ?ex/s]

In [11]:
model = model.eval()
model = model.cuda()

In [13]:
from torch.utils.data import DataLoader
from transformers.data.data_collator import DataCollatorWithPadding
from tqdm.notebook import tqdm
import torch 
results = []

tokenizer.pad_token = tokenizer.eos_token
data_collator = DataCollatorWithPadding(tokenizer)
test_dataloader = DataLoader(
dataset["test"], batch_size=64,  collate_fn=data_collator)
with torch.no_grad():
    for step, batch in enumerate(tqdm(test_dataloader)):
        batch = batch.to('cuda')
        output = model(batch['input_ids'])
        predicted_labels = torch.sigmoid(output.logits)
        results.extend(predicted_labels.cpu().detach().numpy().tolist())

  0%|          | 0/273 [00:00<?, ?it/s]

In [101]:
results = [r[0] for r in results]
import pandas as pd
df = pd.read_csv('/notebooks/test_all.csv')
df['predict'] = results

df.to_csv('/notebooks/test_all_res.csv', index=False)

In [104]:
df['pred_flag']=[True if i>0.5 else False for i in df['predict']]

In [106]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
y_test=df['flag']
y_pred=df['pred_flag']
print(f1_score(y_test, y_pred, average="macro"))
print(precision_score(y_test, y_pred, average="macro"))
print(recall_score(y_test, y_pred, average="macro"))

0.5980229028666889
0.5948928350908507
0.6905143936001288

In [80]:
df_test=pd.read_csv('/notebooks/results/test.csv')
df_input=pd.read_csv('/notebooks/taxonomy.csv')

In [81]:
df_test.columns=['row','pred','label']

In [82]:
df_t=df_input[df_input['group']>=647]

In [83]:
df_t['predict']=list(torch.sigmoid(torch.tensor(df_test['pred'])).numpy())

/tmp/ipykernel_132/837773228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t['predict']=list(torch.sigmoid(torch.tensor(df_test['pred'])).numpy())

In [84]:
df_t['label']=list(df_test['label'])

/tmp/ipykernel_132/3823888313.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t['label']=list(df_test['label'])

In [85]:
df_t=df

In [87]:
df_t

       Unnamed: 0       parent          child  group   flag   predict
0               1     dominion     absolutism    647  False  0.665288
1               2     dominion       monopoly    647  False  0.674395
2               3     dominion  transcendence    647  False  0.626090
3               4     dominion     domination    647  False  0.690800
4               5     dominion   predominance    647  False  0.667308
...           ...          ...            ...    ...    ...       ...
17456       17457         rain         shower    754   True  0.791474
17457       17458         rain       sprinkle    754   True  0.680101
17458       17459  precipitate          sleet    754   True  0.265534
17459       17460  precipitate           snow    754   True  0.440617
17460       17461  precipitate           spat    754   True  0.380239

[17461 rows x 6 columns]

In [ ]:
# import networkx as nx

# def directed_maximum_spanning_tree(parents, children, probabilities):
#     # Create an empty directed graph
#     graph = nx.DiGraph()

#     # Add the nodes to the graph
#     nodes = set(parents + children)
#     for node in nodes:
#         graph.add_node(node)

#     # Add the edges to the graph with their associated weights (probabilities)
#     for i in range(len(parents)):
#         graph.add_edge(parents[i], children[i], weight=probabilities[i])

#     # Initialize the tree
#     tree = nx.DiGraph()

#     # Sort the edges in the graph by weight (in decreasing order)
#     edges = sorted(graph.edges(data=True), key=lambda x: x[2]['weight'], reverse=True)

#     # Add the nodes to the tree
#     for node in graph.nodes():
#         tree.add_node(node)

#     # Iterate over the sorted edges, adding each edge to the tree if it does not create a cycle
#     for edge in edges:
#         if not nx.has_path(tree, edge[1], edge[0]):
#             tree.add_edge(edge[1], edge[0], weight=edge[2]['weight'])

#         # Stop the iteration when the tree has n-1 edges
#         if len(tree.edges()) == len(graph.nodes()) - 1:
#             break

#     return tree

In [14]:
import networkx as nx
forest=[]
for g in set(list(df_t.group)):
    df_tree=df_t[df_t.group==g]
    graph = nx.DiGraph()
    parents=df_tree['parent'].tolist()
    children=df_tree['child'].tolist()
    probabilities=df_tree['predict'].tolist()
    nodes = set(parents + children)
    for node in nodes:
        graph.add_node(node)
    for i in range(len(parents)):
        graph.add_edge(parents[i], children[i], weight=probabilities[i])
    T=nx.maximum_spanning_arborescence(graph)
    df=nx.to_pandas_edgelist(T)
    df['group']=g
    forest.append(df)
    # tree=directed_maximum_spanning_tree(df_tree['parent'].tolist(),df_tree['child'].tolist(),df_tree['predict'].tolist())
    # forest.append(tree)

NameError: name 'df_t' is not defined

In [89]:
res_v2=pd.concat(forest, ignore_index=True)

In [90]:
res_v2

          source         target    weight  group
0       dominion    paramountcy  0.765505    647
1       dominion            raj  0.625795    647
2       dominion          reign  0.655747    647
3       dominion     suzerainty  0.634183    647
4     domination  transcendence  0.707873    647
...          ...            ...       ...    ...
1998        rain        drizzle  0.719938    754
1999        rain           pour  0.632484    754
2000        rain         shower  0.791474    754
2001        rain       sprinkle  0.680101    754
2002     drizzle         sluice  0.343170    754

[2003 rows x 4 columns]

In [91]:
res_v2.columns=['parent','child','weight','group']

In [92]:
res_v2['compare']=res_v2['parent']+res_v2['child']+res_v2['group'].astype(str)

In [93]:
res_v2['group'].value_counts()

665    49
682    48
685    40
662    39
683    39
       ..
677    10
732    10
727    10
705    10
737    10
Name: group, Length: 108, dtype: int64

In [94]:
df_actual.merge(res_v2, on='compare').to_csv('/notebooks/same_all.csv')

In [95]:
df_actual.merge(res_v2, on='compare')

,Unnamed: 0,parent_x,child_x,group_x,flag,predict,label,compare,parent_y,child_y,weight,group_y
0,12869,dominance,absolutism,647,True,0.720197,1,dominanceabsolutism647,dominance,absolutism,0.727166,647
1,12870,dominance,ascendant,647,True,0.731368,1,dominanceascendant647,dominance,ascendant,0.744396,647
2,12871,dominance,domination,647,True,0.759397,1,dominancedomination647,dominance,domination,0.751299,647
3,12872,domination,transcendence,647,True,0.729613,1,dominationtranscendence647,domination,transcendence,0.707873,647
4,12873,dominance,dominion,647,True,0.705614,1,dominancedominion647,dominance,dominion,0.718067,647
...,...,...,...,...,...,...,...,...,...,...,...,...
1038,14867,precipitate,rain,754,True,0.551324,1,precipitaterain754,precipitate,rain,0.506611,754
1039,14868,rain,drizzle,754,True,0.787144,1,raindrizzle754,rain,drizzle,0.719938,754
1040,14869,rain,pour,754,True,0.670678,1,rainpour754,rain,pour,0.632484,754
1041,14872,rain,shower,754,True,0.841348,1,rainshower754,rain,shower,0.791474,754
1042,14873,rain,sprinkle,754,True,0.725750,1,rainsprinkle754,rain,sprinkle,0.680101,754

In [96]:
df_actual.to_csv('/notebooks/actual.csv')

In [97]:
res_v2.to_csv('/notebooks/predict.csv')

In [98]:
len(df_actual.merge(res_v2, on='compare'))/len(df_actual)

0.5194223107569721

In [99]:
len(df_actual.merge(res_v2, on='compare'))/len(res_v2)

0.5207189216175736

In [28]:
forest=[]
for i in set(list(df_t.group)):
    df_tree=df_t[df_t.group==i]
    tree=directed_maximum_spanning_tree(df_tree['parent'].tolist(),df_tree['child'].tolist(),df_tree['predict'].tolist())
    df=nx.to_pandas_edgelist(tree)
    df['group']=i
    forest.append(df)
result = pd.concat(forest, ignore_index=True)

In [29]:
result.columns=['parent','child','weight','group']

In [30]:
result['compare']=result['parent']+result['child']+result['group'].astype(str)

In [31]:
df_actual=df_t[df_t.label==1]

In [32]:
df_actual['compare']=df_actual['parent']+df_actual['child']+df_actual['group'].astype(str)

/tmp/ipykernel_132/1489742617.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_actual['compare']=df_actual['parent']+df_actual['child']+df_actual['group'].astype(str)

In [33]:
df_actual.merge(result, on='compare')

Empty DataFrame
Columns: [Unnamed: 0, parent_x, child_x, group_x, flag, predict, label, compare, parent_y, child_y, weight, group_y]
Index: []

In [34]:
result

           parent      child    weight  group                 compare
0      regulation   dominion  0.652581    647   regulationdominion647
1        dominion  dominance  0.705614    647    dominiondominance647
2      domination  dominance  0.759397    647  dominationdominance647
3     paramountcy   dominion  0.776318    647  paramountcydominion647
4         scepter      reign  0.562737    647         scepterreign647
...           ...        ...       ...    ...                     ...
1998        sleet       snow  0.647799    754            sleetsnow754
1999        sleet     sluice  0.615701    754          sleetsluice754
2000        sheet       snow  0.668230    754            sheetsnow754
2001         pour       rain  0.670678    754             pourrain754
2002      drizzle       rain  0.787144    754          drizzlerain754

[2003 rows x 5 columns]

In [35]:
df_actual

,Unnamed: 0,parent,child,group,flag,predict,label,compare
12869,12869,dominance,absolutism,647,True,0.720197,1,dominanceabsolutism647
12870,12870,dominance,ascendant,647,True,0.731368,1,dominanceascendant647
12871,12871,dominance,domination,647,True,0.759397,1,dominancedomination647
12872,12872,domination,transcendence,647,True,0.729613,1,dominationtranscendence647
12873,12873,dominance,dominion,647,True,0.705614,1,dominancedominion647
...,...,...,...,...,...,...,...,...
14872,14872,rain,shower,754,True,0.841348,1,rainshower754
14873,14873,rain,sprinkle,754,True,0.725750,1,rainsprinkle754
14874,14874,precipitate,sleet,754,True,0.306711,1,precipitatesleet754
14875,14875,precipitate,snow,754,True,0.493274,1,precipitatesnow754
14876,14876,precipitate,spat,754,True,0.416163,1,precipitatespat754

In [76]:
result

            parent        child    weight  group                   compare
0       domination    dominance  0.759397    647    dominationdominance647
1     predominance    dominance  0.703348    647  predominancedominance647
2            reign     dominion  0.678727    647          reigndominion647
3      paramountcy     dominion  0.776318    647    paramountcydominion647
4         monopoly    dominance  0.637977    647      monopolydominance647
...            ...          ...       ...    ...                       ...
1998        shower       sluice  0.635144    754           showersluice754
1999          rain  precipitate  0.551324    754        rainprecipitate754
2000          snow  precipitate  0.493274    754        snowprecipitate754
2001          pour         rain  0.670678    754               pourrain754
2002       drizzle         rain  0.787144    754            drizzlerain754

[2003 rows x 5 columns]

In [77]:
df_actual.merge(result, how='inner', on='compare')

Empty DataFrame
Columns: [Unnamed: 0, parent_x, child_x, group_x, flag, predict, label, compare, parent_y, child_y, weight, group_y]
Index: []

In [55]:
import pandas as pd

# Create example dataframes
df1 = result[['parent','child','group']].reset_index(drop=True).sort_index()
df2 = df_t[df_t.label==1][['parent','child','group']].reset_index(drop=True).sort_index()
# Specify columns to compare
columns_to_compare = ['parent', 'child', 'group']

# Use the compare() function to get the differences between the two dataframes
diff = df1[columns_to_compare].compare(df2[columns_to_compare])

# Calculate the percentage of similarity
similarity = 1 - (len(diff) / (len(df1) + len(df2)) / 2)

# Print the similarity percentage
print("The dataframes are", round(similarity*100,2),"% similar.")

ValueError: Can only compare identically-labeled DataFrame objects

In [ ]:
import networkx as nx

# Define the list of pairs and their associated probabilities
pairs = [(1, 2, 0.5), (1, 3, 0.2), (2, 3, 0.8), (3, 4, 0.4), (4, 5, 0.6)]

# Create an empty graph
graph = nx.Graph()

# Add the nodes to the graph
nodes = set([p[0] for p in pairs] + [p[1] for p in pairs])
for node in nodes:
    graph.add_node(node)

# Add the edges to the graph with their associated weights (probabilities)
for pair in pairs:
    graph.add_edge(pair[0], pair[1], weight=pair[2])

# Obtain the maximum spanning tree using the maximum_spanning_tree() function
max_tree = maximum_spanning_tree(graph)